### ISSUE TITLE
Feature request: add support for Snappy codec.

### ISSUE THREAD

**Issue by twadleigh** [Hydrotoast/Avro.jl#4]
There is already [Snappy.jl](https://github.com/bicycle1885/Snappy.jl) so should be straightforward. I'll do it when I get a chance.

**Comment by Hydrotoast** [comment]
Thanks for looking into this! I will review the changes.

**Comment by Hydrotoast** [comment]
The Travis build is now green after merging these changes. Thanks again @twadleigh !

As an additional note, it seems that this project requires a migration onto the new `Pkg` management system introduced in Julia 1.0. To publish a new version with these changes, project/build configuration are likely to change.
